spring:
#  kafka:
#    properties:
#      schema.registry.url: http://localhost:8081
#      specific.avro.reader: true
#    consumer:
#      auto-offset-reset: earliest
#      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
#
  cloud:
    stream:
      bindings:
        input:
          group: k2p
          contentType: application/*+avro
          destination: inputTopic
          consumer:
            useNativeDecoding: true
        binder:
          brokers: localhost:9092

server:
  port: 8082